# Generated by Django 5.2.7 on 2025-10-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_incidencia_inmueble'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquilinos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propietario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
